version: 0.2

env:
  variables:
    NODE_ENV: "production"

phases:
  install:
    runtime-versions:
      nodejs: 14.x
    commands:
      - npm install -g gatsby

  pre_build:
    commands:
      - npm install

  build:
    commands:
      - gatsby build

  post_build:
    commands:
      ## copy the contents of /public to S3  | Use ${DeployBucket} with CloudFormation
      # aws sync vs cp https://stackoverflow.com/questions/64728076/aws-s3-cp-vs-aws-s3-sync-behavior-and-cost
      # - aws s3 cp --recursive --acl public-read --cache-control="max-age=0, no-cache, no-store, must-revalidate" ./public s3://$DEPLOY_BUCKET
      - aws s3 sync --delete --acl public-read --cache-control="max-age=0, no-cache, no-store, must-revalidate" ./public s3://$DEPLOY_BUCKET
      ## set the cache-control headers for index.html to prevent browser caching | Use ${DeployBucket} with CloudFormation
      # - >
      #   aws s3 cp --acl public-read 
      #   --cache-control="max-age=0, no-cache, no-store, must-revalidate" 
      #   ./public s3://new.victoryatl.com/

      ## invalidate the CloudFront cache for /public | Use ${CloudFrontDistribution} with CloudFormation
      - >
        aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION
        --paths /*

cache:
  paths:
    - 'node_modules/*'
    - '.cache/*'
    - 'data/*'
    - 'public/*'
    - 'WordPress/*'

artifacts:
  files:
    - '**/*'
  base-directory: public