version: 0.2

env:
  variables:
    NODE_ENV: "production"

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install -g gatsby

  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install

  build:
    commands:
      - Building Gatsby website...
      - gatsby build

  post_build:
    commands:
      - echo Build completed on `date`
      
cache:
  paths:
    - './node_modules/**/*'

artifacts:
  files:
    - '**/*'