version: 0.2

env:
  variables:
    NODE_ENV: "staging"

phases:
  install:
    runtime-versions:
      nodejs: 14.x
    commands:
      - npm install -g gatsby

  pre_build:
    commands:
      - npm install

  build:
    commands:
      - gatsby build

  post_build:
    commands:
      - echo "User-agent:*" > ./public/robots.txt
      - echo "Disallow:/" >> ./public/robots.txt
      # copy the contents of /public to S3  | Use ${DeployBucket} with CloudFormation
      - echo "S3 bucket is $DEPLOY_BUCKET"
      - aws s3 sync --delete --acl public-read --cache-control="max-age=0, no-cache, no-store, must-revalidate" ./public s3://$DEPLOY_BUCKET

cache:
  paths:
    - 'node_modules/*'
    - '.cache/*'
    - 'data/*'
    - 'public/*'
    - 'WordPress/*'

artifacts:
  files:
    - '**/*'
  base-directory: public
