version: 0.2

env:
  variables:
    NODE_ENV: "production"

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install -g gatsby

  pre_build:
    commands:
      - npm install

  build:
    commands:
      - gatsby build

cache:
  paths:
    - './node_modules/**/*'