version: "3"
services:
  client:
    platform: linux/amd64
    build:
      context: .
      dockerfile: ./scripts/docker/Dockerfile.dev
    volumes:
      - ./src:/app/src # Links the source files to the running container
    ports:
      - "8001:8000"