FROM node:14.17.2-alpine
WORKDIR /app

# Install dependencies
# Install python/pip
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools
# Install Project dependencies
RUN npm install -g gatsby-cli
RUN node -v

# Configure and Install project
# COPY the package.json file
COPY package.json .
RUN npm update
RUN npm install
# Copy the whole source folder (relative to the Dockerfile)
COPY . .

CMD [ "npm", "run", "start" ]